name: C build

on:
  push:
  pull_request:

jobs:
  setup_environment:
    strategy:
      matrix:
        os:
        - macOS-latest
        - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ConorMacBride/install-package@v1
        with:
          brew: autoconf automake cmake ninja popt python python3 python-setuptools
          apt: clang cmake ninja-build libavahi-client-dev libpopt-dev gdb python3-dev python3-setuptools
      - run: which python3

  make_check:
    needs: setup_environment
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./autogen.sh
      # Setting `python3` helps it find the Homebrew Python on macOS.
      - run: ./configure PYTHON=python3
      - run: make
      - run: make check

  cmake_build:
    needs: setup_environment
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_AUTH=ON
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_GTK=ON
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_AVAHI=OFF
      - run: cmake --build build
