name: C build

on:
  push:
  pull_request:

jobs:
  make_check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false
    uses: ./.github/workflows/compile-env.yml
    with:
      os: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: ./autogen.sh
      # Setting `python3` helps it find the Homebrew Python on macOS.
      - run: ./configure PYTHON=python3
      - run: make
      - run: make check

  cmake_build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false
    uses: ./.github/workflows/compile-env.yml
    with:
      os: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # Build both debug and release to catch different compile issues
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_AUTH=ON
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_GTK=ON
      - run: cmake --build build
      - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_AVAHI=OFF
      - run: cmake --build build
